### ISSUE TITLE
Update README to describe the various jobs, what their inputs are, and how they fit into the workflow

### ISSUE THREAD

**Issue by Cameronwyatt** [rhtconsulting/miq-ci#1]

**Comment by Cameronwyatt** [comment]
@ajsmith thoughts on updated job descriptions? 4bb99e3e5ba1c3e859cdd067d124e8d679996620

**Comment by Cameronwyatt** [comment]
@jsimonelli can you review the README and let me know your thoughts? Are the job descriptions clear enough?

**Comment by jsimonelli** [comment]
here are some of my suggestions:
- Specify which ManageIQ appliance you would target to install stuff

Jenkins Setup
- I would add version tested for Jenkins
- Change the DEV/Test/QA/Prod wording to talk about Regions as opposed to lifecycle environments as not all users use different regions to separate DEV, Test, QA and Prod.  
- Modify all CFME with ManageIQ

**Comment by ajsmith** [comment]
@Cameronwyatt, just for general improvements I'd suggest the following:
- The "Overview" should be one or two sentences which states
  the purpose at a very high level. Requirement and feature
  details should be given their own sections, if those details
  exist.
- Use `code formatting` or "quotes" to improve readability of
  parameters and file names, respectively.
- Be concise. For example, the terms "user-specified", "specified by
  user", and "specific" are sometimes overused. "Available parameters"
  can simply be called "Parameters". Etc.

Maybe @jsimonelli will disagree, but I also think it would be good to have a little bit of text describing how lifecycles are represented as regions, since managing lifecycles is generally a major goal of CI. That said, I still agree that most of the wording should be in terms of regions, not lifecycles.

**Comment by Cameronwyatt** [comment]
Updated partially in commits 84b1a2a793036e99dad72805ac1c130baaf86581 and e1dbb4cc73ae2f6226433fb0c0e489053e5f6a08.

Still need to convert the job titles from using DEV, TEST, etc. to using region10, region20, etc.
